### ISSUE TITLE
What mods are you going to put in this Modpack?

### ISSUE THREAD

**Issue by panda2134** [JackyWangMislantiaJnirvana/Minecraft-Classic-164-Modpack#1]
:-)

**Comment by JackyJnirvana** [comment]
Let's see...... I want to build my live modpack here.
I will collect some classic mods to build this pack, the more the better.
Do you want to join me? :）

**Comment by panda2134** [comment]
For I'm now busy making redstone music,I'm sorry to tell you that I do not
have time mod-packing these days:-(

2015-12-12 17:48 GMT+08:00 JackyWangMislantiaJnirvana <
notifications@github.com>:

**Comment by JackyJnirvana** [comment]
Ok, welcom whenever you can come!
